### ISSUE TITLE
Unable to build on travis

### ISSUE THREAD

**Issue by martmists** [MTG/essentia#717]
My project requires essentia and is tested on Travis. However, with this config:
```yaml
dist: xenial

before_install:
  - sudo apt update
  - sudo apt install libfftw3-dev libav-tools

install:
  - "cd .."
  - "git clone https://github.com/MTG/essentia"
  - "cd essentia"
  - "./waf configure --build-static --with-python"
  - "./waf"
  - "./waf install"
  ...
``` 
I get the following:
![image](https://user-images.githubusercontent.com/16361449/39367084-1b11e0a6-4a36-11e8-84f8-ee3569e669f1.png)
This is great, so it should work now, right?
....nope
![image](https://user-images.githubusercontent.com/16361449/39367150-3eb547fa-4a36-11e8-8de1-b26b3ea8f4d3.png)
