### ISSUE TITLE
In MusicExtractor.compute: Descriptor metadata.audio_properties.analysis_sample_rate could not be found in pool

### ISSUE THREAD

**Issue by simonefrancia** [MTG/essentia#762]
Hi, I'm trying to use Python version of Essentia with Gaia in order to use high level features.
My full profile file (yaml) is this:
```
startTime: 30
endTime: 35
outputFrames: 0
outputFormat: json
requireMbid: false
indent: 4

lowlevel:
    frameSize: 2048
    hopSize: 1024
    zeroPadding: 0
    windowType: blackmanharris62
    silentFrames: noise
    #stats: ["mean", "var", "median", "min", "max", "dmean", "dmean2", "dvar", "dvar2", "stdev"]

average_loudness:
   frameSize: 88200
   hopSize: 44100
   windowType: hann
   silentFrames: noise

rhythm:
    method: degara
    minTempo: 40
    maxTempo: 208
     stats: ["mean", "var", "median", "min", "max", "dmean", "dmean2", "dvar", "dvar2", "stdev"]
tonal:
   frameSize: 4096
   hopSize: 2048
   zeroPadding: 0
   windowType: blackmanharris62
   silentFrames: noise
    stats: ["mean", "var", "median", "min", "max", "dmean", "dmean2", "dvar", "dvar2", "stdev"]

highlevel:
    compute: 0
    svm_models: ['svm_models/danceability.history']
```

Low level features are ok, but if I add last tag in file profile, there is this error:

```('Error processing', '......', ':', 'In MusicExtractor.compute: Descriptor metadata.audio_properties.analysis_sample_rate could not be found in pool')```

Thanks
