### ISSUE TITLE
A prebuild streaming_extractor_music with high level 

### ISSUE THREAD

**Issue by halaei** [MTG/essentia#973]
Thanks for the amazing work. But it is extremely hard to make things working.

I just want streaming_extractor_music static binary that supports high-level Gaia models in https://essentia.upf.edu/svm_models/, preferably the lastest versions.
My attempts to build in my system have already failed. I couldn't find a docker image that has gaia2. And I couldn't make my image from https://github.com/MTG/essentia-docker/blob/master/nightly/Dockerfile.ubuntu18.04-nightly.

I will thank you a lot if you give us a docker image / prebuild binary with gaia2 and models and a simple profile.yml file like this:

```yml
highlevel:
  compute: 1
  svm_models: ['models/danceability.history', 'models/genre_electronic.history', 'models/ismir04_rhythm.history', 'models/mood_electronic.history', 'models/mood_relaxed.history', 'models/timbre.history', 'models/gender.history', 'models/genre_rosamerica.history', 'models/mood_acoustic.history', 'models/mood_happy.history', 'models/mood_sad.history',   'models/tonal_atonal.history', 'models/genre_dortmund.history', 'models/genre_tzanetakis.history', 'models/mood_aggressive.history', 'models/mood_party.history', 'models/moods_mirex.history','models/voice_instrumental.history']
```
