### ISSUE TITLE
Segmentation fault in music extractor while extracting some high level featueres

### ISSUE THREAD

**Issue by halaei** [MTG/essentia#974]
I build v2.1_beta5 statically with gaia, and downloaded the svm models from https://essentia.upf.edu/svm_models/essentia-extractor-svm_models-v2.1_beta5.tar.gz. Most of the models are fine:
```yml
highlevel:
  compute: 1
  svm_models:
    - 'models/danceability.history'
    - 'models/gender.history'
    - 'models/timbre.history'
    - 'models/mood_acoustic.history'
    - 'models/mood_aggressive.history'
    - 'models/mood_electronic.history'
    - 'models/mood_happy.history'
    - 'models/mood_party.history'
    - 'models/mood_relaxed.history'
    - 'models/mood_sad.history'
    - 'models/tonal_atonal.history'
    - 'models/ismir04_rhythm.history'
    - 'models/genre_rosamerica.history'
    - 'models/genre_tzanetakis.history'
```
However, using the following 4 models results in segmentation fault:
```yml
   - 'models/moods_mirex.history'
   - 'models/genre_electronic.history'
   - 'models/genre_dortmund.history'
   - 'models/voice_instrumental.history'
```
I think this means these 4 models are either corrupted or out of date?
